_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.5
            "6": 4.41.2
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 4096
dataset:
    value: merged/full
device:
    value: cuda
epochs:
    value: 20
learning_rate:
    value: 1
num_factor:
    value: 12
seed:
    value: 291124
